/*
 * MIT License
 *
 * Copyright (c) 2018 Aberic Yang
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node/NodeElection.proto

package cn.aberic.bother.entity.proto.node;

public final class NodeElectionProto {
  private NodeElectionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeElectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NodeElection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 当前节点竞选对象所属智能合约Hash
     * </pre>
     *
     * <code>string contractHash = 1;</code>
     */
    String getContractHash();
    /**
     * <pre>
     * 当前节点竞选对象所属智能合约Hash
     * </pre>
     *
     * <code>string contractHash = 1;</code>
     */
    com.google.protobuf.ByteString
        getContractHashBytes();

    /**
     * <pre>
     * 当前Hash合约竞选节点所属子节点总数
     * </pre>
     *
     * <code>int32 nodeCount = 2;</code>
     */
    int getNodeCount();

    /**
     * <pre>
     * 当前选举节点基本信息集合 &lt;= 50
     * </pre>
     *
     * <code>repeated .NodeBase nodeBases = 3;</code>
     */
    java.util.List<NodeBaseProto.NodeBase>
        getNodeBasesList();
    /**
     * <pre>
     * 当前选举节点基本信息集合 &lt;= 50
     * </pre>
     *
     * <code>repeated .NodeBase nodeBases = 3;</code>
     */
    NodeBaseProto.NodeBase getNodeBases(int index);
    /**
     * <pre>
     * 当前选举节点基本信息集合 &lt;= 50
     * </pre>
     *
     * <code>repeated .NodeBase nodeBases = 3;</code>
     */
    int getNodeBasesCount();
    /**
     * <pre>
     * 当前选举节点基本信息集合 &lt;= 50
     * </pre>
     *
     * <code>repeated .NodeBase nodeBases = 3;</code>
     */
    java.util.List<? extends NodeBaseProto.NodeBaseOrBuilder>
        getNodeBasesOrBuilderList();
    /**
     * <pre>
     * 当前选举节点基本信息集合 &lt;= 50
     * </pre>
     *
     * <code>repeated .NodeBase nodeBases = 3;</code>
     */
    NodeBaseProto.NodeBaseOrBuilder getNodeBasesOrBuilder(
            int index);

    /**
     * <pre>
     * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
     * </pre>
     *
     * <code>repeated string addresses = 4;</code>
     */
    java.util.List<String>
        getAddressesList();
    /**
     * <pre>
     * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
     * </pre>
     *
     * <code>repeated string addresses = 4;</code>
     */
    int getAddressesCount();
    /**
     * <pre>
     * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
     * </pre>
     *
     * <code>repeated string addresses = 4;</code>
     */
    String getAddresses(int index);
    /**
     * <pre>
     * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
     * </pre>
     *
     * <code>repeated string addresses = 4;</code>
     */
    com.google.protobuf.ByteString
        getAddressesBytes(int index);

    /**
     * <pre>
     * 当前Hash合约其他竞选节点其下属子节点个数集合
     * </pre>
     *
     * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
     */
    int getNodesCountCount();
    /**
     * <pre>
     * 当前Hash合约其他竞选节点其下属子节点个数集合
     * </pre>
     *
     * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
     */
    boolean containsNodesCount(
            String key);
    /**
     * Use {@link #getNodesCountMap()} instead.
     */
    @Deprecated
    java.util.Map<String, Integer>
    getNodesCount();
    /**
     * <pre>
     * 当前Hash合约其他竞选节点其下属子节点个数集合
     * </pre>
     *
     * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
     */
    java.util.Map<String, Integer>
    getNodesCountMap();
    /**
     * <pre>
     * 当前Hash合约其他竞选节点其下属子节点个数集合
     * </pre>
     *
     * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
     */

    int getNodesCountOrDefault(
            String key,
            int defaultValue);
    /**
     * <pre>
     * 当前Hash合约其他竞选节点其下属子节点个数集合
     * </pre>
     *
     * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
     */

    int getNodesCountOrThrow(
            String key);

    /**
     * <pre>
     * 当前待打包交易集合
     * </pre>
     *
     * <code>repeated .Transaction transactions = 6;</code>
     */
    java.util.List<cn.aberic.bother.entity.proto.block.TransactionProto.Transaction>
        getTransactionsList();
    /**
     * <pre>
     * 当前待打包交易集合
     * </pre>
     *
     * <code>repeated .Transaction transactions = 6;</code>
     */
    cn.aberic.bother.entity.proto.block.TransactionProto.Transaction getTransactions(int index);
    /**
     * <pre>
     * 当前待打包交易集合
     * </pre>
     *
     * <code>repeated .Transaction transactions = 6;</code>
     */
    int getTransactionsCount();
    /**
     * <pre>
     * 当前待打包交易集合
     * </pre>
     *
     * <code>repeated .Transaction transactions = 6;</code>
     */
    java.util.List<? extends cn.aberic.bother.entity.proto.block.TransactionProto.TransactionOrBuilder>
        getTransactionsOrBuilderList();
    /**
     * <pre>
     * 当前待打包交易集合
     * </pre>
     *
     * <code>repeated .Transaction transactions = 6;</code>
     */
    cn.aberic.bother.entity.proto.block.TransactionProto.TransactionOrBuilder getTransactionsOrBuilder(
            int index);
  }
  /**
   * <pre>
   * 当前节点竞选对象
   * </pre>
   *
   * Protobuf type {@code NodeElection}
   */
  public  static final class NodeElection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NodeElection)
      NodeElectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeElection.newBuilder() to construct.
    private NodeElection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeElection() {
      contractHash_ = "";
      nodeCount_ = 0;
      nodeBases_ = java.util.Collections.emptyList();
      addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      transactions_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodeElection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              contractHash_ = s;
              break;
            }
            case 16: {

              nodeCount_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                nodeBases_ = new java.util.ArrayList<NodeBaseProto.NodeBase>();
                mutable_bitField0_ |= 0x00000004;
              }
              nodeBases_.add(
                  input.readMessage(NodeBaseProto.NodeBase.parser(), extensionRegistry));
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                addresses_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              addresses_.add(s);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                nodesCount_ = com.google.protobuf.MapField.newMapField(
                    NodesCountDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<String, Integer>
              nodesCount__ = input.readMessage(
                  NodesCountDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              nodesCount_.getMutableMap().put(
                  nodesCount__.getKey(), nodesCount__.getValue());
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                transactions_ = new java.util.ArrayList<cn.aberic.bother.entity.proto.block.TransactionProto.Transaction>();
                mutable_bitField0_ |= 0x00000020;
              }
              transactions_.add(
                  input.readMessage(cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          nodeBases_ = java.util.Collections.unmodifiableList(nodeBases_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          addresses_ = addresses_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NodeElectionProto.internal_static_NodeElection_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetNodesCount();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NodeElectionProto.internal_static_NodeElection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NodeElectionProto.NodeElection.class, NodeElectionProto.NodeElection.Builder.class);
    }

    private int bitField0_;
    public static final int CONTRACTHASH_FIELD_NUMBER = 1;
    private volatile Object contractHash_;
    /**
     * <pre>
     * 当前节点竞选对象所属智能合约Hash
     * </pre>
     *
     * <code>string contractHash = 1;</code>
     */
    public String getContractHash() {
      Object ref = contractHash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        contractHash_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 当前节点竞选对象所属智能合约Hash
     * </pre>
     *
     * <code>string contractHash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContractHashBytes() {
      Object ref = contractHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        contractHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODECOUNT_FIELD_NUMBER = 2;
    private int nodeCount_;
    /**
     * <pre>
     * 当前Hash合约竞选节点所属子节点总数
     * </pre>
     *
     * <code>int32 nodeCount = 2;</code>
     */
    public int getNodeCount() {
      return nodeCount_;
    }

    public static final int NODEBASES_FIELD_NUMBER = 3;
    private java.util.List<NodeBaseProto.NodeBase> nodeBases_;
    /**
     * <pre>
     * 当前选举节点基本信息集合 &lt;= 50
     * </pre>
     *
     * <code>repeated .NodeBase nodeBases = 3;</code>
     */
    public java.util.List<NodeBaseProto.NodeBase> getNodeBasesList() {
      return nodeBases_;
    }
    /**
     * <pre>
     * 当前选举节点基本信息集合 &lt;= 50
     * </pre>
     *
     * <code>repeated .NodeBase nodeBases = 3;</code>
     */
    public java.util.List<? extends NodeBaseProto.NodeBaseOrBuilder>
        getNodeBasesOrBuilderList() {
      return nodeBases_;
    }
    /**
     * <pre>
     * 当前选举节点基本信息集合 &lt;= 50
     * </pre>
     *
     * <code>repeated .NodeBase nodeBases = 3;</code>
     */
    public int getNodeBasesCount() {
      return nodeBases_.size();
    }
    /**
     * <pre>
     * 当前选举节点基本信息集合 &lt;= 50
     * </pre>
     *
     * <code>repeated .NodeBase nodeBases = 3;</code>
     */
    public NodeBaseProto.NodeBase getNodeBases(int index) {
      return nodeBases_.get(index);
    }
    /**
     * <pre>
     * 当前选举节点基本信息集合 &lt;= 50
     * </pre>
     *
     * <code>repeated .NodeBase nodeBases = 3;</code>
     */
    public NodeBaseProto.NodeBaseOrBuilder getNodeBasesOrBuilder(
        int index) {
      return nodeBases_.get(index);
    }

    public static final int ADDRESSES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList addresses_;
    /**
     * <pre>
     * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
     * </pre>
     *
     * <code>repeated string addresses = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddressesList() {
      return addresses_;
    }
    /**
     * <pre>
     * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
     * </pre>
     *
     * <code>repeated string addresses = 4;</code>
     */
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <pre>
     * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
     * </pre>
     *
     * <code>repeated string addresses = 4;</code>
     */
    public String getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <pre>
     * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
     * </pre>
     *
     * <code>repeated string addresses = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAddressesBytes(int index) {
      return addresses_.getByteString(index);
    }

    public static final int NODESCOUNT_FIELD_NUMBER = 5;
    private static final class NodesCountDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, Integer>newDefaultInstance(
                  NodeElectionProto.internal_static_NodeElection_NodesCountEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        String, Integer> nodesCount_;
    private com.google.protobuf.MapField<String, Integer>
    internalGetNodesCount() {
      if (nodesCount_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            NodesCountDefaultEntryHolder.defaultEntry);
      }
      return nodesCount_;
    }

    public int getNodesCountCount() {
      return internalGetNodesCount().getMap().size();
    }
    /**
     * <pre>
     * 当前Hash合约其他竞选节点其下属子节点个数集合
     * </pre>
     *
     * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
     */

    public boolean containsNodesCount(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetNodesCount().getMap().containsKey(key);
    }
    /**
     * Use {@link #getNodesCountMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, Integer> getNodesCount() {
      return getNodesCountMap();
    }
    /**
     * <pre>
     * 当前Hash合约其他竞选节点其下属子节点个数集合
     * </pre>
     *
     * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
     */

    public java.util.Map<String, Integer> getNodesCountMap() {
      return internalGetNodesCount().getMap();
    }
    /**
     * <pre>
     * 当前Hash合约其他竞选节点其下属子节点个数集合
     * </pre>
     *
     * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
     */

    public int getNodesCountOrDefault(
        String key,
        int defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Integer> map =
          internalGetNodesCount().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 当前Hash合约其他竞选节点其下属子节点个数集合
     * </pre>
     *
     * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
     */

    public int getNodesCountOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Integer> map =
          internalGetNodesCount().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TRANSACTIONS_FIELD_NUMBER = 6;
    private java.util.List<cn.aberic.bother.entity.proto.block.TransactionProto.Transaction> transactions_;
    /**
     * <pre>
     * 当前待打包交易集合
     * </pre>
     *
     * <code>repeated .Transaction transactions = 6;</code>
     */
    public java.util.List<cn.aberic.bother.entity.proto.block.TransactionProto.Transaction> getTransactionsList() {
      return transactions_;
    }
    /**
     * <pre>
     * 当前待打包交易集合
     * </pre>
     *
     * <code>repeated .Transaction transactions = 6;</code>
     */
    public java.util.List<? extends cn.aberic.bother.entity.proto.block.TransactionProto.TransactionOrBuilder>
        getTransactionsOrBuilderList() {
      return transactions_;
    }
    /**
     * <pre>
     * 当前待打包交易集合
     * </pre>
     *
     * <code>repeated .Transaction transactions = 6;</code>
     */
    public int getTransactionsCount() {
      return transactions_.size();
    }
    /**
     * <pre>
     * 当前待打包交易集合
     * </pre>
     *
     * <code>repeated .Transaction transactions = 6;</code>
     */
    public cn.aberic.bother.entity.proto.block.TransactionProto.Transaction getTransactions(int index) {
      return transactions_.get(index);
    }
    /**
     * <pre>
     * 当前待打包交易集合
     * </pre>
     *
     * <code>repeated .Transaction transactions = 6;</code>
     */
    public cn.aberic.bother.entity.proto.block.TransactionProto.TransactionOrBuilder getTransactionsOrBuilder(
        int index) {
      return transactions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getContractHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contractHash_);
      }
      if (nodeCount_ != 0) {
        output.writeInt32(2, nodeCount_);
      }
      for (int i = 0; i < nodeBases_.size(); i++) {
        output.writeMessage(3, nodeBases_.get(i));
      }
      for (int i = 0; i < addresses_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, addresses_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetNodesCount(),
          NodesCountDefaultEntryHolder.defaultEntry,
          5);
      for (int i = 0; i < transactions_.size(); i++) {
        output.writeMessage(6, transactions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getContractHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contractHash_);
      }
      if (nodeCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, nodeCount_);
      }
      for (int i = 0; i < nodeBases_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, nodeBases_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addresses_.size(); i++) {
          dataSize += computeStringSizeNoTag(addresses_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddressesList().size();
      }
      for (java.util.Map.Entry<String, Integer> entry
           : internalGetNodesCount().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, Integer>
        nodesCount__ = NodesCountDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, nodesCount__);
      }
      for (int i = 0; i < transactions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, transactions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NodeElectionProto.NodeElection)) {
        return super.equals(obj);
      }
      NodeElectionProto.NodeElection other = (NodeElectionProto.NodeElection) obj;

      boolean result = true;
      result = result && getContractHash()
          .equals(other.getContractHash());
      result = result && (getNodeCount()
          == other.getNodeCount());
      result = result && getNodeBasesList()
          .equals(other.getNodeBasesList());
      result = result && getAddressesList()
          .equals(other.getAddressesList());
      result = result && internalGetNodesCount().equals(
          other.internalGetNodesCount());
      result = result && getTransactionsList()
          .equals(other.getTransactionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTRACTHASH_FIELD_NUMBER;
      hash = (53 * hash) + getContractHash().hashCode();
      hash = (37 * hash) + NODECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getNodeCount();
      if (getNodeBasesCount() > 0) {
        hash = (37 * hash) + NODEBASES_FIELD_NUMBER;
        hash = (53 * hash) + getNodeBasesList().hashCode();
      }
      if (getAddressesCount() > 0) {
        hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
        hash = (53 * hash) + getAddressesList().hashCode();
      }
      if (!internalGetNodesCount().getMap().isEmpty()) {
        hash = (37 * hash) + NODESCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetNodesCount().hashCode();
      }
      if (getTransactionsCount() > 0) {
        hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NodeElectionProto.NodeElection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NodeElectionProto.NodeElection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NodeElectionProto.NodeElection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NodeElectionProto.NodeElection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NodeElectionProto.NodeElection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NodeElectionProto.NodeElection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NodeElectionProto.NodeElection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NodeElectionProto.NodeElection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NodeElectionProto.NodeElection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NodeElectionProto.NodeElection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NodeElectionProto.NodeElection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NodeElectionProto.NodeElection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NodeElectionProto.NodeElection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 当前节点竞选对象
     * </pre>
     *
     * Protobuf type {@code NodeElection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NodeElection)
        NodeElectionProto.NodeElectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NodeElectionProto.internal_static_NodeElection_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetNodesCount();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableNodesCount();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NodeElectionProto.internal_static_NodeElection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NodeElectionProto.NodeElection.class, NodeElectionProto.NodeElection.Builder.class);
      }

      // Construct using cn.aberic.bother.entity.proto.node.NodeElectionProto.NodeElection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeBasesFieldBuilder();
          getTransactionsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        contractHash_ = "";

        nodeCount_ = 0;

        if (nodeBasesBuilder_ == null) {
          nodeBases_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          nodeBasesBuilder_.clear();
        }
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableNodesCount().clear();
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NodeElectionProto.internal_static_NodeElection_descriptor;
      }

      @Override
      public NodeElectionProto.NodeElection getDefaultInstanceForType() {
        return NodeElectionProto.NodeElection.getDefaultInstance();
      }

      @Override
      public NodeElectionProto.NodeElection build() {
        NodeElectionProto.NodeElection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NodeElectionProto.NodeElection buildPartial() {
        NodeElectionProto.NodeElection result = new NodeElectionProto.NodeElection(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.contractHash_ = contractHash_;
        result.nodeCount_ = nodeCount_;
        if (nodeBasesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            nodeBases_ = java.util.Collections.unmodifiableList(nodeBases_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.nodeBases_ = nodeBases_;
        } else {
          result.nodeBases_ = nodeBasesBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          addresses_ = addresses_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.addresses_ = addresses_;
        result.nodesCount_ = internalGetNodesCount();
        result.nodesCount_.makeImmutable();
        if (transactionsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            transactions_ = java.util.Collections.unmodifiableList(transactions_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.transactions_ = transactions_;
        } else {
          result.transactions_ = transactionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NodeElectionProto.NodeElection) {
          return mergeFrom((NodeElectionProto.NodeElection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NodeElectionProto.NodeElection other) {
        if (other == NodeElectionProto.NodeElection.getDefaultInstance()) return this;
        if (!other.getContractHash().isEmpty()) {
          contractHash_ = other.contractHash_;
          onChanged();
        }
        if (other.getNodeCount() != 0) {
          setNodeCount(other.getNodeCount());
        }
        if (nodeBasesBuilder_ == null) {
          if (!other.nodeBases_.isEmpty()) {
            if (nodeBases_.isEmpty()) {
              nodeBases_ = other.nodeBases_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureNodeBasesIsMutable();
              nodeBases_.addAll(other.nodeBases_);
            }
            onChanged();
          }
        } else {
          if (!other.nodeBases_.isEmpty()) {
            if (nodeBasesBuilder_.isEmpty()) {
              nodeBasesBuilder_.dispose();
              nodeBasesBuilder_ = null;
              nodeBases_ = other.nodeBases_;
              bitField0_ = (bitField0_ & ~0x00000004);
              nodeBasesBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeBasesFieldBuilder() : null;
            } else {
              nodeBasesBuilder_.addAllMessages(other.nodeBases_);
            }
          }
        }
        if (!other.addresses_.isEmpty()) {
          if (addresses_.isEmpty()) {
            addresses_ = other.addresses_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAddressesIsMutable();
            addresses_.addAll(other.addresses_);
          }
          onChanged();
        }
        internalGetMutableNodesCount().mergeFrom(
            other.internalGetNodesCount());
        if (transactionsBuilder_ == null) {
          if (!other.transactions_.isEmpty()) {
            if (transactions_.isEmpty()) {
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureTransactionsIsMutable();
              transactions_.addAll(other.transactions_);
            }
            onChanged();
          }
        } else {
          if (!other.transactions_.isEmpty()) {
            if (transactionsBuilder_.isEmpty()) {
              transactionsBuilder_.dispose();
              transactionsBuilder_ = null;
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000020);
              transactionsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTransactionsFieldBuilder() : null;
            } else {
              transactionsBuilder_.addAllMessages(other.transactions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NodeElectionProto.NodeElection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NodeElectionProto.NodeElection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object contractHash_ = "";
      /**
       * <pre>
       * 当前节点竞选对象所属智能合约Hash
       * </pre>
       *
       * <code>string contractHash = 1;</code>
       */
      public String getContractHash() {
        Object ref = contractHash_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          contractHash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 当前节点竞选对象所属智能合约Hash
       * </pre>
       *
       * <code>string contractHash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContractHashBytes() {
        Object ref = contractHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          contractHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 当前节点竞选对象所属智能合约Hash
       * </pre>
       *
       * <code>string contractHash = 1;</code>
       */
      public Builder setContractHash(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        contractHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前节点竞选对象所属智能合约Hash
       * </pre>
       *
       * <code>string contractHash = 1;</code>
       */
      public Builder clearContractHash() {

        contractHash_ = getDefaultInstance().getContractHash();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前节点竞选对象所属智能合约Hash
       * </pre>
       *
       * <code>string contractHash = 1;</code>
       */
      public Builder setContractHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        contractHash_ = value;
        onChanged();
        return this;
      }

      private int nodeCount_ ;
      /**
       * <pre>
       * 当前Hash合约竞选节点所属子节点总数
       * </pre>
       *
       * <code>int32 nodeCount = 2;</code>
       */
      public int getNodeCount() {
        return nodeCount_;
      }
      /**
       * <pre>
       * 当前Hash合约竞选节点所属子节点总数
       * </pre>
       *
       * <code>int32 nodeCount = 2;</code>
       */
      public Builder setNodeCount(int value) {

        nodeCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前Hash合约竞选节点所属子节点总数
       * </pre>
       *
       * <code>int32 nodeCount = 2;</code>
       */
      public Builder clearNodeCount() {

        nodeCount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<NodeBaseProto.NodeBase> nodeBases_ =
        java.util.Collections.emptyList();
      private void ensureNodeBasesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          nodeBases_ = new java.util.ArrayList<NodeBaseProto.NodeBase>(nodeBases_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          NodeBaseProto.NodeBase, NodeBaseProto.NodeBase.Builder, NodeBaseProto.NodeBaseOrBuilder> nodeBasesBuilder_;

      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public java.util.List<NodeBaseProto.NodeBase> getNodeBasesList() {
        if (nodeBasesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodeBases_);
        } else {
          return nodeBasesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public int getNodeBasesCount() {
        if (nodeBasesBuilder_ == null) {
          return nodeBases_.size();
        } else {
          return nodeBasesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public NodeBaseProto.NodeBase getNodeBases(int index) {
        if (nodeBasesBuilder_ == null) {
          return nodeBases_.get(index);
        } else {
          return nodeBasesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public Builder setNodeBases(
          int index, NodeBaseProto.NodeBase value) {
        if (nodeBasesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeBasesIsMutable();
          nodeBases_.set(index, value);
          onChanged();
        } else {
          nodeBasesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public Builder setNodeBases(
          int index, NodeBaseProto.NodeBase.Builder builderForValue) {
        if (nodeBasesBuilder_ == null) {
          ensureNodeBasesIsMutable();
          nodeBases_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeBasesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public Builder addNodeBases(NodeBaseProto.NodeBase value) {
        if (nodeBasesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeBasesIsMutable();
          nodeBases_.add(value);
          onChanged();
        } else {
          nodeBasesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public Builder addNodeBases(
          int index, NodeBaseProto.NodeBase value) {
        if (nodeBasesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeBasesIsMutable();
          nodeBases_.add(index, value);
          onChanged();
        } else {
          nodeBasesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public Builder addNodeBases(
          NodeBaseProto.NodeBase.Builder builderForValue) {
        if (nodeBasesBuilder_ == null) {
          ensureNodeBasesIsMutable();
          nodeBases_.add(builderForValue.build());
          onChanged();
        } else {
          nodeBasesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public Builder addNodeBases(
          int index, NodeBaseProto.NodeBase.Builder builderForValue) {
        if (nodeBasesBuilder_ == null) {
          ensureNodeBasesIsMutable();
          nodeBases_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeBasesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public Builder addAllNodeBases(
          Iterable<? extends NodeBaseProto.NodeBase> values) {
        if (nodeBasesBuilder_ == null) {
          ensureNodeBasesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeBases_);
          onChanged();
        } else {
          nodeBasesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public Builder clearNodeBases() {
        if (nodeBasesBuilder_ == null) {
          nodeBases_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          nodeBasesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public Builder removeNodeBases(int index) {
        if (nodeBasesBuilder_ == null) {
          ensureNodeBasesIsMutable();
          nodeBases_.remove(index);
          onChanged();
        } else {
          nodeBasesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public NodeBaseProto.NodeBase.Builder getNodeBasesBuilder(
          int index) {
        return getNodeBasesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public NodeBaseProto.NodeBaseOrBuilder getNodeBasesOrBuilder(
          int index) {
        if (nodeBasesBuilder_ == null) {
          return nodeBases_.get(index);  } else {
          return nodeBasesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public java.util.List<? extends NodeBaseProto.NodeBaseOrBuilder>
           getNodeBasesOrBuilderList() {
        if (nodeBasesBuilder_ != null) {
          return nodeBasesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodeBases_);
        }
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public NodeBaseProto.NodeBase.Builder addNodeBasesBuilder() {
        return getNodeBasesFieldBuilder().addBuilder(
            NodeBaseProto.NodeBase.getDefaultInstance());
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public NodeBaseProto.NodeBase.Builder addNodeBasesBuilder(
          int index) {
        return getNodeBasesFieldBuilder().addBuilder(
            index, NodeBaseProto.NodeBase.getDefaultInstance());
      }
      /**
       * <pre>
       * 当前选举节点基本信息集合 &lt;= 50
       * </pre>
       *
       * <code>repeated .NodeBase nodeBases = 3;</code>
       */
      public java.util.List<NodeBaseProto.NodeBase.Builder>
           getNodeBasesBuilderList() {
        return getNodeBasesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          NodeBaseProto.NodeBase, NodeBaseProto.NodeBase.Builder, NodeBaseProto.NodeBaseOrBuilder>
          getNodeBasesFieldBuilder() {
        if (nodeBasesBuilder_ == null) {
          nodeBasesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              NodeBaseProto.NodeBase, NodeBaseProto.NodeBase.Builder, NodeBaseProto.NodeBaseOrBuilder>(
                  nodeBases_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          nodeBases_ = null;
        }
        return nodeBasesBuilder_;
      }

      private com.google.protobuf.LazyStringList addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          addresses_ = new com.google.protobuf.LazyStringArrayList(addresses_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
       * </pre>
       *
       * <code>repeated string addresses = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddressesList() {
        return addresses_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
       * </pre>
       *
       * <code>repeated string addresses = 4;</code>
       */
      public int getAddressesCount() {
        return addresses_.size();
      }
      /**
       * <pre>
       * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
       * </pre>
       *
       * <code>repeated string addresses = 4;</code>
       */
      public String getAddresses(int index) {
        return addresses_.get(index);
      }
      /**
       * <pre>
       * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
       * </pre>
       *
       * <code>repeated string addresses = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAddressesBytes(int index) {
        return addresses_.getByteString(index);
      }
      /**
       * <pre>
       * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
       * </pre>
       *
       * <code>repeated string addresses = 4;</code>
       */
      public Builder setAddresses(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
       * </pre>
       *
       * <code>repeated string addresses = 4;</code>
       */
      public Builder addAddresses(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
       * </pre>
       *
       * <code>repeated string addresses = 4;</code>
       */
      public Builder addAllAddresses(
          Iterable<String> values) {
        ensureAddressesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addresses_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
       * </pre>
       *
       * <code>repeated string addresses = 4;</code>
       */
      public Builder clearAddresses() {
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 从其它竞选节点获取其两个子节点的而组成的备用节点集合 &lt;= 100
       * </pre>
       *
       * <code>repeated string addresses = 4;</code>
       */
      public Builder addAddressesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, Integer> nodesCount_;
      private com.google.protobuf.MapField<String, Integer>
      internalGetNodesCount() {
        if (nodesCount_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              NodesCountDefaultEntryHolder.defaultEntry);
        }
        return nodesCount_;
      }
      private com.google.protobuf.MapField<String, Integer>
      internalGetMutableNodesCount() {
        onChanged();;
        if (nodesCount_ == null) {
          nodesCount_ = com.google.protobuf.MapField.newMapField(
              NodesCountDefaultEntryHolder.defaultEntry);
        }
        if (!nodesCount_.isMutable()) {
          nodesCount_ = nodesCount_.copy();
        }
        return nodesCount_;
      }

      public int getNodesCountCount() {
        return internalGetNodesCount().getMap().size();
      }
      /**
       * <pre>
       * 当前Hash合约其他竞选节点其下属子节点个数集合
       * </pre>
       *
       * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
       */

      public boolean containsNodesCount(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetNodesCount().getMap().containsKey(key);
      }
      /**
       * Use {@link #getNodesCountMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, Integer> getNodesCount() {
        return getNodesCountMap();
      }
      /**
       * <pre>
       * 当前Hash合约其他竞选节点其下属子节点个数集合
       * </pre>
       *
       * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
       */

      public java.util.Map<String, Integer> getNodesCountMap() {
        return internalGetNodesCount().getMap();
      }
      /**
       * <pre>
       * 当前Hash合约其他竞选节点其下属子节点个数集合
       * </pre>
       *
       * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
       */

      public int getNodesCountOrDefault(
          String key,
          int defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Integer> map =
            internalGetNodesCount().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * 当前Hash合约其他竞选节点其下属子节点个数集合
       * </pre>
       *
       * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
       */

      public int getNodesCountOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Integer> map =
            internalGetNodesCount().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearNodesCount() {
        internalGetMutableNodesCount().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * 当前Hash合约其他竞选节点其下属子节点个数集合
       * </pre>
       *
       * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
       */

      public Builder removeNodesCount(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableNodesCount().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, Integer>
      getMutableNodesCount() {
        return internalGetMutableNodesCount().getMutableMap();
      }
      /**
       * <pre>
       * 当前Hash合约其他竞选节点其下属子节点个数集合
       * </pre>
       *
       * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
       */
      public Builder putNodesCount(
          String key,
          int value) {
        if (key == null) { throw new NullPointerException(); }

        internalGetMutableNodesCount().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * 当前Hash合约其他竞选节点其下属子节点个数集合
       * </pre>
       *
       * <code>map&lt;string, int32&gt; nodesCount = 5;</code>
       */

      public Builder putAllNodesCount(
          java.util.Map<String, Integer> values) {
        internalGetMutableNodesCount().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.util.List<cn.aberic.bother.entity.proto.block.TransactionProto.Transaction> transactions_ =
        java.util.Collections.emptyList();
      private void ensureTransactionsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          transactions_ = new java.util.ArrayList<cn.aberic.bother.entity.proto.block.TransactionProto.Transaction>(transactions_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.aberic.bother.entity.proto.block.TransactionProto.Transaction, cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.Builder, cn.aberic.bother.entity.proto.block.TransactionProto.TransactionOrBuilder> transactionsBuilder_;

      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public java.util.List<cn.aberic.bother.entity.proto.block.TransactionProto.Transaction> getTransactionsList() {
        if (transactionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(transactions_);
        } else {
          return transactionsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public int getTransactionsCount() {
        if (transactionsBuilder_ == null) {
          return transactions_.size();
        } else {
          return transactionsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public cn.aberic.bother.entity.proto.block.TransactionProto.Transaction getTransactions(int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);
        } else {
          return transactionsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public Builder setTransactions(
          int index, cn.aberic.bother.entity.proto.block.TransactionProto.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.set(index, value);
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public Builder setTransactions(
          int index, cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.set(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public Builder addTransactions(cn.aberic.bother.entity.proto.block.TransactionProto.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public Builder addTransactions(
          int index, cn.aberic.bother.entity.proto.block.TransactionProto.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(index, value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public Builder addTransactions(
          cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public Builder addTransactions(
          int index, cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public Builder addAllTransactions(
          Iterable<? extends cn.aberic.bother.entity.proto.block.TransactionProto.Transaction> values) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, transactions_);
          onChanged();
        } else {
          transactionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public Builder clearTransactions() {
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public Builder removeTransactions(int index) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.remove(index);
          onChanged();
        } else {
          transactionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.Builder getTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public cn.aberic.bother.entity.proto.block.TransactionProto.TransactionOrBuilder getTransactionsOrBuilder(
          int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);  } else {
          return transactionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public java.util.List<? extends cn.aberic.bother.entity.proto.block.TransactionProto.TransactionOrBuilder>
           getTransactionsOrBuilderList() {
        if (transactionsBuilder_ != null) {
          return transactionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(transactions_);
        }
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.Builder addTransactionsBuilder() {
        return getTransactionsFieldBuilder().addBuilder(
            cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.getDefaultInstance());
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.Builder addTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().addBuilder(
            index, cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.getDefaultInstance());
      }
      /**
       * <pre>
       * 当前待打包交易集合
       * </pre>
       *
       * <code>repeated .Transaction transactions = 6;</code>
       */
      public java.util.List<cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.Builder>
           getTransactionsBuilderList() {
        return getTransactionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.aberic.bother.entity.proto.block.TransactionProto.Transaction, cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.Builder, cn.aberic.bother.entity.proto.block.TransactionProto.TransactionOrBuilder>
          getTransactionsFieldBuilder() {
        if (transactionsBuilder_ == null) {
          transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.aberic.bother.entity.proto.block.TransactionProto.Transaction, cn.aberic.bother.entity.proto.block.TransactionProto.Transaction.Builder, cn.aberic.bother.entity.proto.block.TransactionProto.TransactionOrBuilder>(
                  transactions_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          transactions_ = null;
        }
        return transactionsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NodeElection)
    }

    // @@protoc_insertion_point(class_scope:NodeElection)
    private static final NodeElectionProto.NodeElection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NodeElectionProto.NodeElection();
    }

    public static NodeElectionProto.NodeElection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeElection>
        PARSER = new com.google.protobuf.AbstractParser<NodeElection>() {
      @Override
      public NodeElection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeElection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeElection> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NodeElection> getParserForType() {
      return PARSER;
    }

    @Override
    public NodeElectionProto.NodeElection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeElection_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeElection_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeElection_NodesCountEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeElection_NodesCountEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027node/NodeElection.proto\032\023node/NodeBase" +
      ".proto\032\027block/Transaction.proto\"\362\001\n\014Node" +
      "Election\022\024\n\014contractHash\030\001 \001(\t\022\021\n\tnodeCo" +
      "unt\030\002 \001(\005\022\034\n\tnodeBases\030\003 \003(\0132\t.NodeBase\022" +
      "\021\n\taddresses\030\004 \003(\t\0221\n\nnodesCount\030\005 \003(\0132\035" +
      ".NodeElection.NodesCountEntry\022\"\n\014transac" +
      "tions\030\006 \003(\0132\014.Transaction\0321\n\017NodesCountE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001B7\n\"" +
      "cn.aberic.bother.entity.proto.nodeB\021Node" +
      "ElectionProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          NodeBaseProto.getDescriptor(),
          cn.aberic.bother.entity.proto.block.TransactionProto.getDescriptor(),
        }, assigner);
    internal_static_NodeElection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NodeElection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeElection_descriptor,
        new String[] { "ContractHash", "NodeCount", "NodeBases", "Addresses", "NodesCount", "Transactions", });
    internal_static_NodeElection_NodesCountEntry_descriptor =
      internal_static_NodeElection_descriptor.getNestedTypes().get(0);
    internal_static_NodeElection_NodesCountEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeElection_NodesCountEntry_descriptor,
        new String[] { "Key", "Value", });
    NodeBaseProto.getDescriptor();
    cn.aberic.bother.entity.proto.block.TransactionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
