// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transaction.proto

package cn.aberic.bother.entity.proto;

public final class TransactionProto {
  private TransactionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 本次写入值链码hash
     * </pre>
     *
     * <code>string hash = 1;</code>
     */
    java.lang.String getHash();
    /**
     * <pre>
     * 本次写入值链码hash
     * </pre>
     *
     * <code>string hash = 1;</code>
     */
    com.google.protobuf.ByteString
        getHashBytes();

    /**
     * <pre>
     * 本次写入值所用合约名称
     * </pre>
     *
     * <code>string contractName = 2;</code>
     */
    java.lang.String getContractName();
    /**
     * <pre>
     * 本次写入值所用合约名称
     * </pre>
     *
     * <code>string contractName = 2;</code>
     */
    com.google.protobuf.ByteString
        getContractNameBytes();

    /**
     * <pre>
     * 本次写入值所用合约版本
     * </pre>
     *
     * <code>string contractVersion = 3;</code>
     */
    java.lang.String getContractVersion();
    /**
     * <pre>
     * 本次写入值所用合约版本
     * </pre>
     *
     * <code>string contractVersion = 3;</code>
     */
    com.google.protobuf.ByteString
        getContractVersionBytes();

    /**
     * <pre>
     * 发起方
     * </pre>
     *
     * <code>string creator = 4;</code>
     */
    java.lang.String getCreator();
    /**
     * <pre>
     * 发起方
     * </pre>
     *
     * <code>string creator = 4;</code>
     */
    com.google.protobuf.ByteString
        getCreatorBytes();

    /**
     * <pre>
     * 发起方签名
     * </pre>
     *
     * <code>string sign = 5;</code>
     */
    java.lang.String getSign();
    /**
     * <pre>
     * 发起方签名
     * </pre>
     *
     * <code>string sign = 5;</code>
     */
    com.google.protobuf.ByteString
        getSignBytes();

    /**
     * <pre>
     * 交易读写集
     * </pre>
     *
     * <code>.RWSet rwSet = 6;</code>
     */
    boolean hasRwSet();
    /**
     * <pre>
     * 交易读写集
     * </pre>
     *
     * <code>.RWSet rwSet = 6;</code>
     */
    cn.aberic.bother.entity.proto.RWSetProto.RWSet getRwSet();
    /**
     * <pre>
     * 交易读写集
     * </pre>
     *
     * <code>.RWSet rwSet = 6;</code>
     */
    cn.aberic.bother.entity.proto.RWSetProto.RWSetOrBuilder getRwSetOrBuilder();

    /**
     * <pre>
     * 交易时间戳
     * </pre>
     *
     * <code>uint64 timestamp = 7;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     * 交易hash
     * </pre>
     *
     * <code>string txHash = 8;</code>
     */
    java.lang.String getTxHash();
    /**
     * <pre>
     * 交易hash
     * </pre>
     *
     * <code>string txHash = 8;</code>
     */
    com.google.protobuf.ByteString
        getTxHashBytes();

    /**
     * <pre>
     * 交易状态
     * </pre>
     *
     * <code>.Transaction.TransactionStatus transactionStatusCode = 9;</code>
     */
    int getTransactionStatusCodeValue();
    /**
     * <pre>
     * 交易状态
     * </pre>
     *
     * <code>.Transaction.TransactionStatus transactionStatusCode = 9;</code>
     */
    cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus getTransactionStatusCode();

    /**
     * <pre>
     * 交易错误信息
     * </pre>
     *
     * <code>string errorMessage = 10;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <pre>
     * 交易错误信息
     * </pre>
     *
     * <code>string errorMessage = 10;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <pre>
     * 交易索引hash
     * </pre>
     *
     * <code>string dataStorageHash = 11;</code>
     */
    java.lang.String getDataStorageHash();
    /**
     * <pre>
     * 交易索引hash
     * </pre>
     *
     * <code>string dataStorageHash = 11;</code>
     */
    com.google.protobuf.ByteString
        getDataStorageHashBytes();

    /**
     * <pre>
     * 交易时间戳转字符串——yyyy/MM/dd HH:mm:ss
     * </pre>
     *
     * <code>string time = 12;</code>
     */
    java.lang.String getTime();
    /**
     * <pre>
     * 交易时间戳转字符串——yyyy/MM/dd HH:mm:ss
     * </pre>
     *
     * <code>string time = 12;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <pre>
     * 智能合约请求对象
     * </pre>
     *
     * <code>.Request request = 13;</code>
     */
    boolean hasRequest();
    /**
     * <pre>
     * 智能合约请求对象
     * </pre>
     *
     * <code>.Request request = 13;</code>
     */
    cn.aberic.bother.entity.proto.RequestProto.Request getRequest();
    /**
     * <pre>
     * 智能合约请求对象
     * </pre>
     *
     * <code>.Request request = 13;</code>
     */
    cn.aberic.bother.entity.proto.RequestProto.RequestOrBuilder getRequestOrBuilder();

    /**
     * <pre>
     * 账户 ECC 公钥
     * </pre>
     *
     * <code>string pubECCKey = 14;</code>
     */
    java.lang.String getPubECCKey();
    /**
     * <pre>
     * 账户 ECC 公钥
     * </pre>
     *
     * <code>string pubECCKey = 14;</code>
     */
    com.google.protobuf.ByteString
        getPubECCKeyBytes();
  }
  /**
   * Protobuf type {@code Transaction}
   */
  public  static final class Transaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Transaction)
      TransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transaction() {
      hash_ = "";
      contractName_ = "";
      contractVersion_ = "";
      creator_ = "";
      sign_ = "";
      timestamp_ = 0L;
      txHash_ = "";
      transactionStatusCode_ = 0;
      errorMessage_ = "";
      dataStorageHash_ = "";
      time_ = "";
      pubECCKey_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hash_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              contractName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              contractVersion_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              creator_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              sign_ = s;
              break;
            }
            case 50: {
              cn.aberic.bother.entity.proto.RWSetProto.RWSet.Builder subBuilder = null;
              if (rwSet_ != null) {
                subBuilder = rwSet_.toBuilder();
              }
              rwSet_ = input.readMessage(cn.aberic.bother.entity.proto.RWSetProto.RWSet.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rwSet_);
                rwSet_ = subBuilder.buildPartial();
              }

              break;
            }
            case 56: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              txHash_ = s;
              break;
            }
            case 72: {
              int rawValue = input.readEnum();

              transactionStatusCode_ = rawValue;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              errorMessage_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              dataStorageHash_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 106: {
              cn.aberic.bother.entity.proto.RequestProto.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(cn.aberic.bother.entity.proto.RequestProto.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              pubECCKey_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.aberic.bother.entity.proto.TransactionProto.internal_static_Transaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.aberic.bother.entity.proto.TransactionProto.internal_static_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.aberic.bother.entity.proto.TransactionProto.Transaction.class, cn.aberic.bother.entity.proto.TransactionProto.Transaction.Builder.class);
    }

    /**
     * Protobuf enum {@code Transaction.TransactionStatus}
     */
    public enum TransactionStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0),
      /**
       * <code>FAIL = 1;</code>
       */
      FAIL(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>FAIL = 1;</code>
       */
      public static final int FAIL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TransactionStatus valueOf(int value) {
        return forNumber(value);
      }

      public static TransactionStatus forNumber(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TransactionStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TransactionStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TransactionStatus>() {
              public TransactionStatus findValueByNumber(int number) {
                return TransactionStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.aberic.bother.entity.proto.TransactionProto.Transaction.getDescriptor().getEnumTypes().get(0);
      }

      private static final TransactionStatus[] VALUES = values();

      public static TransactionStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TransactionStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Transaction.TransactionStatus)
    }

    public static final int HASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object hash_;
    /**
     * <pre>
     * 本次写入值链码hash
     * </pre>
     *
     * <code>string hash = 1;</code>
     */
    public java.lang.String getHash() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hash_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 本次写入值链码hash
     * </pre>
     *
     * <code>string hash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTRACTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object contractName_;
    /**
     * <pre>
     * 本次写入值所用合约名称
     * </pre>
     *
     * <code>string contractName = 2;</code>
     */
    public java.lang.String getContractName() {
      java.lang.Object ref = contractName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 本次写入值所用合约名称
     * </pre>
     *
     * <code>string contractName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContractNameBytes() {
      java.lang.Object ref = contractName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTRACTVERSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object contractVersion_;
    /**
     * <pre>
     * 本次写入值所用合约版本
     * </pre>
     *
     * <code>string contractVersion = 3;</code>
     */
    public java.lang.String getContractVersion() {
      java.lang.Object ref = contractVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 本次写入值所用合约版本
     * </pre>
     *
     * <code>string contractVersion = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContractVersionBytes() {
      java.lang.Object ref = contractVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATOR_FIELD_NUMBER = 4;
    private volatile java.lang.Object creator_;
    /**
     * <pre>
     * 发起方
     * </pre>
     *
     * <code>string creator = 4;</code>
     */
    public java.lang.String getCreator() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发起方
     * </pre>
     *
     * <code>string creator = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGN_FIELD_NUMBER = 5;
    private volatile java.lang.Object sign_;
    /**
     * <pre>
     * 发起方签名
     * </pre>
     *
     * <code>string sign = 5;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发起方签名
     * </pre>
     *
     * <code>string sign = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RWSET_FIELD_NUMBER = 6;
    private cn.aberic.bother.entity.proto.RWSetProto.RWSet rwSet_;
    /**
     * <pre>
     * 交易读写集
     * </pre>
     *
     * <code>.RWSet rwSet = 6;</code>
     */
    public boolean hasRwSet() {
      return rwSet_ != null;
    }
    /**
     * <pre>
     * 交易读写集
     * </pre>
     *
     * <code>.RWSet rwSet = 6;</code>
     */
    public cn.aberic.bother.entity.proto.RWSetProto.RWSet getRwSet() {
      return rwSet_ == null ? cn.aberic.bother.entity.proto.RWSetProto.RWSet.getDefaultInstance() : rwSet_;
    }
    /**
     * <pre>
     * 交易读写集
     * </pre>
     *
     * <code>.RWSet rwSet = 6;</code>
     */
    public cn.aberic.bother.entity.proto.RWSetProto.RWSetOrBuilder getRwSetOrBuilder() {
      return getRwSet();
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private long timestamp_;
    /**
     * <pre>
     * 交易时间戳
     * </pre>
     *
     * <code>uint64 timestamp = 7;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TXHASH_FIELD_NUMBER = 8;
    private volatile java.lang.Object txHash_;
    /**
     * <pre>
     * 交易hash
     * </pre>
     *
     * <code>string txHash = 8;</code>
     */
    public java.lang.String getTxHash() {
      java.lang.Object ref = txHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txHash_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 交易hash
     * </pre>
     *
     * <code>string txHash = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTxHashBytes() {
      java.lang.Object ref = txHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSACTIONSTATUSCODE_FIELD_NUMBER = 9;
    private int transactionStatusCode_;
    /**
     * <pre>
     * 交易状态
     * </pre>
     *
     * <code>.Transaction.TransactionStatus transactionStatusCode = 9;</code>
     */
    public int getTransactionStatusCodeValue() {
      return transactionStatusCode_;
    }
    /**
     * <pre>
     * 交易状态
     * </pre>
     *
     * <code>.Transaction.TransactionStatus transactionStatusCode = 9;</code>
     */
    public cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus getTransactionStatusCode() {
      @SuppressWarnings("deprecation")
      cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus result = cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus.valueOf(transactionStatusCode_);
      return result == null ? cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus.UNRECOGNIZED : result;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 10;
    private volatile java.lang.Object errorMessage_;
    /**
     * <pre>
     * 交易错误信息
     * </pre>
     *
     * <code>string errorMessage = 10;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 交易错误信息
     * </pre>
     *
     * <code>string errorMessage = 10;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATASTORAGEHASH_FIELD_NUMBER = 11;
    private volatile java.lang.Object dataStorageHash_;
    /**
     * <pre>
     * 交易索引hash
     * </pre>
     *
     * <code>string dataStorageHash = 11;</code>
     */
    public java.lang.String getDataStorageHash() {
      java.lang.Object ref = dataStorageHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataStorageHash_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 交易索引hash
     * </pre>
     *
     * <code>string dataStorageHash = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDataStorageHashBytes() {
      java.lang.Object ref = dataStorageHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataStorageHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 12;
    private volatile java.lang.Object time_;
    /**
     * <pre>
     * 交易时间戳转字符串——yyyy/MM/dd HH:mm:ss
     * </pre>
     *
     * <code>string time = 12;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 交易时间戳转字符串——yyyy/MM/dd HH:mm:ss
     * </pre>
     *
     * <code>string time = 12;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_FIELD_NUMBER = 13;
    private cn.aberic.bother.entity.proto.RequestProto.Request request_;
    /**
     * <pre>
     * 智能合约请求对象
     * </pre>
     *
     * <code>.Request request = 13;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <pre>
     * 智能合约请求对象
     * </pre>
     *
     * <code>.Request request = 13;</code>
     */
    public cn.aberic.bother.entity.proto.RequestProto.Request getRequest() {
      return request_ == null ? cn.aberic.bother.entity.proto.RequestProto.Request.getDefaultInstance() : request_;
    }
    /**
     * <pre>
     * 智能合约请求对象
     * </pre>
     *
     * <code>.Request request = 13;</code>
     */
    public cn.aberic.bother.entity.proto.RequestProto.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int PUBECCKEY_FIELD_NUMBER = 14;
    private volatile java.lang.Object pubECCKey_;
    /**
     * <pre>
     * 账户 ECC 公钥
     * </pre>
     *
     * <code>string pubECCKey = 14;</code>
     */
    public java.lang.String getPubECCKey() {
      java.lang.Object ref = pubECCKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pubECCKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 账户 ECC 公钥
     * </pre>
     *
     * <code>string pubECCKey = 14;</code>
     */
    public com.google.protobuf.ByteString
        getPubECCKeyBytes() {
      java.lang.Object ref = pubECCKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pubECCKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hash_);
      }
      if (!getContractNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contractName_);
      }
      if (!getContractVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, contractVersion_);
      }
      if (!getCreatorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, creator_);
      }
      if (!getSignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sign_);
      }
      if (rwSet_ != null) {
        output.writeMessage(6, getRwSet());
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(7, timestamp_);
      }
      if (!getTxHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, txHash_);
      }
      if (transactionStatusCode_ != cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus.SUCCESS.getNumber()) {
        output.writeEnum(9, transactionStatusCode_);
      }
      if (!getErrorMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, errorMessage_);
      }
      if (!getDataStorageHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, dataStorageHash_);
      }
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, time_);
      }
      if (request_ != null) {
        output.writeMessage(13, getRequest());
      }
      if (!getPubECCKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, pubECCKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hash_);
      }
      if (!getContractNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contractName_);
      }
      if (!getContractVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, contractVersion_);
      }
      if (!getCreatorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, creator_);
      }
      if (!getSignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sign_);
      }
      if (rwSet_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getRwSet());
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, timestamp_);
      }
      if (!getTxHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, txHash_);
      }
      if (transactionStatusCode_ != cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, transactionStatusCode_);
      }
      if (!getErrorMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, errorMessage_);
      }
      if (!getDataStorageHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, dataStorageHash_);
      }
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, time_);
      }
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getRequest());
      }
      if (!getPubECCKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, pubECCKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.aberic.bother.entity.proto.TransactionProto.Transaction)) {
        return super.equals(obj);
      }
      cn.aberic.bother.entity.proto.TransactionProto.Transaction other = (cn.aberic.bother.entity.proto.TransactionProto.Transaction) obj;

      boolean result = true;
      result = result && getHash()
          .equals(other.getHash());
      result = result && getContractName()
          .equals(other.getContractName());
      result = result && getContractVersion()
          .equals(other.getContractVersion());
      result = result && getCreator()
          .equals(other.getCreator());
      result = result && getSign()
          .equals(other.getSign());
      result = result && (hasRwSet() == other.hasRwSet());
      if (hasRwSet()) {
        result = result && getRwSet()
            .equals(other.getRwSet());
      }
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getTxHash()
          .equals(other.getTxHash());
      result = result && transactionStatusCode_ == other.transactionStatusCode_;
      result = result && getErrorMessage()
          .equals(other.getErrorMessage());
      result = result && getDataStorageHash()
          .equals(other.getDataStorageHash());
      result = result && getTime()
          .equals(other.getTime());
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && getPubECCKey()
          .equals(other.getPubECCKey());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (37 * hash) + CONTRACTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getContractName().hashCode();
      hash = (37 * hash) + CONTRACTVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getContractVersion().hashCode();
      hash = (37 * hash) + CREATOR_FIELD_NUMBER;
      hash = (53 * hash) + getCreator().hashCode();
      hash = (37 * hash) + SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getSign().hashCode();
      if (hasRwSet()) {
        hash = (37 * hash) + RWSET_FIELD_NUMBER;
        hash = (53 * hash) + getRwSet().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + TXHASH_FIELD_NUMBER;
      hash = (53 * hash) + getTxHash().hashCode();
      hash = (37 * hash) + TRANSACTIONSTATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + transactionStatusCode_;
      hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMessage().hashCode();
      hash = (37 * hash) + DATASTORAGEHASH_FIELD_NUMBER;
      hash = (53 * hash) + getDataStorageHash().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + PUBECCKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPubECCKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.aberic.bother.entity.proto.TransactionProto.Transaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Transaction)
        cn.aberic.bother.entity.proto.TransactionProto.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.aberic.bother.entity.proto.TransactionProto.internal_static_Transaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.aberic.bother.entity.proto.TransactionProto.internal_static_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.aberic.bother.entity.proto.TransactionProto.Transaction.class, cn.aberic.bother.entity.proto.TransactionProto.Transaction.Builder.class);
      }

      // Construct using cn.aberic.bother.entity.proto.TransactionProto.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hash_ = "";

        contractName_ = "";

        contractVersion_ = "";

        creator_ = "";

        sign_ = "";

        if (rwSetBuilder_ == null) {
          rwSet_ = null;
        } else {
          rwSet_ = null;
          rwSetBuilder_ = null;
        }
        timestamp_ = 0L;

        txHash_ = "";

        transactionStatusCode_ = 0;

        errorMessage_ = "";

        dataStorageHash_ = "";

        time_ = "";

        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        pubECCKey_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.aberic.bother.entity.proto.TransactionProto.internal_static_Transaction_descriptor;
      }

      @java.lang.Override
      public cn.aberic.bother.entity.proto.TransactionProto.Transaction getDefaultInstanceForType() {
        return cn.aberic.bother.entity.proto.TransactionProto.Transaction.getDefaultInstance();
      }

      @java.lang.Override
      public cn.aberic.bother.entity.proto.TransactionProto.Transaction build() {
        cn.aberic.bother.entity.proto.TransactionProto.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.aberic.bother.entity.proto.TransactionProto.Transaction buildPartial() {
        cn.aberic.bother.entity.proto.TransactionProto.Transaction result = new cn.aberic.bother.entity.proto.TransactionProto.Transaction(this);
        result.hash_ = hash_;
        result.contractName_ = contractName_;
        result.contractVersion_ = contractVersion_;
        result.creator_ = creator_;
        result.sign_ = sign_;
        if (rwSetBuilder_ == null) {
          result.rwSet_ = rwSet_;
        } else {
          result.rwSet_ = rwSetBuilder_.build();
        }
        result.timestamp_ = timestamp_;
        result.txHash_ = txHash_;
        result.transactionStatusCode_ = transactionStatusCode_;
        result.errorMessage_ = errorMessage_;
        result.dataStorageHash_ = dataStorageHash_;
        result.time_ = time_;
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.pubECCKey_ = pubECCKey_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.aberic.bother.entity.proto.TransactionProto.Transaction) {
          return mergeFrom((cn.aberic.bother.entity.proto.TransactionProto.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.aberic.bother.entity.proto.TransactionProto.Transaction other) {
        if (other == cn.aberic.bother.entity.proto.TransactionProto.Transaction.getDefaultInstance()) return this;
        if (!other.getHash().isEmpty()) {
          hash_ = other.hash_;
          onChanged();
        }
        if (!other.getContractName().isEmpty()) {
          contractName_ = other.contractName_;
          onChanged();
        }
        if (!other.getContractVersion().isEmpty()) {
          contractVersion_ = other.contractVersion_;
          onChanged();
        }
        if (!other.getCreator().isEmpty()) {
          creator_ = other.creator_;
          onChanged();
        }
        if (!other.getSign().isEmpty()) {
          sign_ = other.sign_;
          onChanged();
        }
        if (other.hasRwSet()) {
          mergeRwSet(other.getRwSet());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getTxHash().isEmpty()) {
          txHash_ = other.txHash_;
          onChanged();
        }
        if (other.transactionStatusCode_ != 0) {
          setTransactionStatusCodeValue(other.getTransactionStatusCodeValue());
        }
        if (!other.getErrorMessage().isEmpty()) {
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (!other.getDataStorageHash().isEmpty()) {
          dataStorageHash_ = other.dataStorageHash_;
          onChanged();
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (!other.getPubECCKey().isEmpty()) {
          pubECCKey_ = other.pubECCKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.aberic.bother.entity.proto.TransactionProto.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.aberic.bother.entity.proto.TransactionProto.Transaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hash_ = "";
      /**
       * <pre>
       * 本次写入值链码hash
       * </pre>
       *
       * <code>string hash = 1;</code>
       */
      public java.lang.String getHash() {
        java.lang.Object ref = hash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 本次写入值链码hash
       * </pre>
       *
       * <code>string hash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHashBytes() {
        java.lang.Object ref = hash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 本次写入值链码hash
       * </pre>
       *
       * <code>string hash = 1;</code>
       */
      public Builder setHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 本次写入值链码hash
       * </pre>
       *
       * <code>string hash = 1;</code>
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 本次写入值链码hash
       * </pre>
       *
       * <code>string hash = 1;</code>
       */
      public Builder setHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contractName_ = "";
      /**
       * <pre>
       * 本次写入值所用合约名称
       * </pre>
       *
       * <code>string contractName = 2;</code>
       */
      public java.lang.String getContractName() {
        java.lang.Object ref = contractName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contractName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 本次写入值所用合约名称
       * </pre>
       *
       * <code>string contractName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContractNameBytes() {
        java.lang.Object ref = contractName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 本次写入值所用合约名称
       * </pre>
       *
       * <code>string contractName = 2;</code>
       */
      public Builder setContractName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contractName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 本次写入值所用合约名称
       * </pre>
       *
       * <code>string contractName = 2;</code>
       */
      public Builder clearContractName() {
        
        contractName_ = getDefaultInstance().getContractName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 本次写入值所用合约名称
       * </pre>
       *
       * <code>string contractName = 2;</code>
       */
      public Builder setContractNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contractName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contractVersion_ = "";
      /**
       * <pre>
       * 本次写入值所用合约版本
       * </pre>
       *
       * <code>string contractVersion = 3;</code>
       */
      public java.lang.String getContractVersion() {
        java.lang.Object ref = contractVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contractVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 本次写入值所用合约版本
       * </pre>
       *
       * <code>string contractVersion = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContractVersionBytes() {
        java.lang.Object ref = contractVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 本次写入值所用合约版本
       * </pre>
       *
       * <code>string contractVersion = 3;</code>
       */
      public Builder setContractVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contractVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 本次写入值所用合约版本
       * </pre>
       *
       * <code>string contractVersion = 3;</code>
       */
      public Builder clearContractVersion() {
        
        contractVersion_ = getDefaultInstance().getContractVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 本次写入值所用合约版本
       * </pre>
       *
       * <code>string contractVersion = 3;</code>
       */
      public Builder setContractVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contractVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object creator_ = "";
      /**
       * <pre>
       * 发起方
       * </pre>
       *
       * <code>string creator = 4;</code>
       */
      public java.lang.String getCreator() {
        java.lang.Object ref = creator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 发起方
       * </pre>
       *
       * <code>string creator = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        java.lang.Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发起方
       * </pre>
       *
       * <code>string creator = 4;</code>
       */
      public Builder setCreator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        creator_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发起方
       * </pre>
       *
       * <code>string creator = 4;</code>
       */
      public Builder clearCreator() {
        
        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发起方
       * </pre>
       *
       * <code>string creator = 4;</code>
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        creator_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sign_ = "";
      /**
       * <pre>
       * 发起方签名
       * </pre>
       *
       * <code>string sign = 5;</code>
       */
      public java.lang.String getSign() {
        java.lang.Object ref = sign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sign_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 发起方签名
       * </pre>
       *
       * <code>string sign = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        java.lang.Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发起方签名
       * </pre>
       *
       * <code>string sign = 5;</code>
       */
      public Builder setSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发起方签名
       * </pre>
       *
       * <code>string sign = 5;</code>
       */
      public Builder clearSign() {
        
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发起方签名
       * </pre>
       *
       * <code>string sign = 5;</code>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sign_ = value;
        onChanged();
        return this;
      }

      private cn.aberic.bother.entity.proto.RWSetProto.RWSet rwSet_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.aberic.bother.entity.proto.RWSetProto.RWSet, cn.aberic.bother.entity.proto.RWSetProto.RWSet.Builder, cn.aberic.bother.entity.proto.RWSetProto.RWSetOrBuilder> rwSetBuilder_;
      /**
       * <pre>
       * 交易读写集
       * </pre>
       *
       * <code>.RWSet rwSet = 6;</code>
       */
      public boolean hasRwSet() {
        return rwSetBuilder_ != null || rwSet_ != null;
      }
      /**
       * <pre>
       * 交易读写集
       * </pre>
       *
       * <code>.RWSet rwSet = 6;</code>
       */
      public cn.aberic.bother.entity.proto.RWSetProto.RWSet getRwSet() {
        if (rwSetBuilder_ == null) {
          return rwSet_ == null ? cn.aberic.bother.entity.proto.RWSetProto.RWSet.getDefaultInstance() : rwSet_;
        } else {
          return rwSetBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 交易读写集
       * </pre>
       *
       * <code>.RWSet rwSet = 6;</code>
       */
      public Builder setRwSet(cn.aberic.bother.entity.proto.RWSetProto.RWSet value) {
        if (rwSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rwSet_ = value;
          onChanged();
        } else {
          rwSetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 交易读写集
       * </pre>
       *
       * <code>.RWSet rwSet = 6;</code>
       */
      public Builder setRwSet(
          cn.aberic.bother.entity.proto.RWSetProto.RWSet.Builder builderForValue) {
        if (rwSetBuilder_ == null) {
          rwSet_ = builderForValue.build();
          onChanged();
        } else {
          rwSetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 交易读写集
       * </pre>
       *
       * <code>.RWSet rwSet = 6;</code>
       */
      public Builder mergeRwSet(cn.aberic.bother.entity.proto.RWSetProto.RWSet value) {
        if (rwSetBuilder_ == null) {
          if (rwSet_ != null) {
            rwSet_ =
              cn.aberic.bother.entity.proto.RWSetProto.RWSet.newBuilder(rwSet_).mergeFrom(value).buildPartial();
          } else {
            rwSet_ = value;
          }
          onChanged();
        } else {
          rwSetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 交易读写集
       * </pre>
       *
       * <code>.RWSet rwSet = 6;</code>
       */
      public Builder clearRwSet() {
        if (rwSetBuilder_ == null) {
          rwSet_ = null;
          onChanged();
        } else {
          rwSet_ = null;
          rwSetBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 交易读写集
       * </pre>
       *
       * <code>.RWSet rwSet = 6;</code>
       */
      public cn.aberic.bother.entity.proto.RWSetProto.RWSet.Builder getRwSetBuilder() {
        
        onChanged();
        return getRwSetFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 交易读写集
       * </pre>
       *
       * <code>.RWSet rwSet = 6;</code>
       */
      public cn.aberic.bother.entity.proto.RWSetProto.RWSetOrBuilder getRwSetOrBuilder() {
        if (rwSetBuilder_ != null) {
          return rwSetBuilder_.getMessageOrBuilder();
        } else {
          return rwSet_ == null ?
              cn.aberic.bother.entity.proto.RWSetProto.RWSet.getDefaultInstance() : rwSet_;
        }
      }
      /**
       * <pre>
       * 交易读写集
       * </pre>
       *
       * <code>.RWSet rwSet = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.aberic.bother.entity.proto.RWSetProto.RWSet, cn.aberic.bother.entity.proto.RWSetProto.RWSet.Builder, cn.aberic.bother.entity.proto.RWSetProto.RWSetOrBuilder> 
          getRwSetFieldBuilder() {
        if (rwSetBuilder_ == null) {
          rwSetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.aberic.bother.entity.proto.RWSetProto.RWSet, cn.aberic.bother.entity.proto.RWSetProto.RWSet.Builder, cn.aberic.bother.entity.proto.RWSetProto.RWSetOrBuilder>(
                  getRwSet(),
                  getParentForChildren(),
                  isClean());
          rwSet_ = null;
        }
        return rwSetBuilder_;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * 交易时间戳
       * </pre>
       *
       * <code>uint64 timestamp = 7;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 交易时间戳
       * </pre>
       *
       * <code>uint64 timestamp = 7;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易时间戳
       * </pre>
       *
       * <code>uint64 timestamp = 7;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object txHash_ = "";
      /**
       * <pre>
       * 交易hash
       * </pre>
       *
       * <code>string txHash = 8;</code>
       */
      public java.lang.String getTxHash() {
        java.lang.Object ref = txHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 交易hash
       * </pre>
       *
       * <code>string txHash = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTxHashBytes() {
        java.lang.Object ref = txHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 交易hash
       * </pre>
       *
       * <code>string txHash = 8;</code>
       */
      public Builder setTxHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易hash
       * </pre>
       *
       * <code>string txHash = 8;</code>
       */
      public Builder clearTxHash() {
        
        txHash_ = getDefaultInstance().getTxHash();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易hash
       * </pre>
       *
       * <code>string txHash = 8;</code>
       */
      public Builder setTxHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txHash_ = value;
        onChanged();
        return this;
      }

      private int transactionStatusCode_ = 0;
      /**
       * <pre>
       * 交易状态
       * </pre>
       *
       * <code>.Transaction.TransactionStatus transactionStatusCode = 9;</code>
       */
      public int getTransactionStatusCodeValue() {
        return transactionStatusCode_;
      }
      /**
       * <pre>
       * 交易状态
       * </pre>
       *
       * <code>.Transaction.TransactionStatus transactionStatusCode = 9;</code>
       */
      public Builder setTransactionStatusCodeValue(int value) {
        transactionStatusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易状态
       * </pre>
       *
       * <code>.Transaction.TransactionStatus transactionStatusCode = 9;</code>
       */
      public cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus getTransactionStatusCode() {
        @SuppressWarnings("deprecation")
        cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus result = cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus.valueOf(transactionStatusCode_);
        return result == null ? cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 交易状态
       * </pre>
       *
       * <code>.Transaction.TransactionStatus transactionStatusCode = 9;</code>
       */
      public Builder setTransactionStatusCode(cn.aberic.bother.entity.proto.TransactionProto.Transaction.TransactionStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        transactionStatusCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易状态
       * </pre>
       *
       * <code>.Transaction.TransactionStatus transactionStatusCode = 9;</code>
       */
      public Builder clearTransactionStatusCode() {
        
        transactionStatusCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <pre>
       * 交易错误信息
       * </pre>
       *
       * <code>string errorMessage = 10;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 交易错误信息
       * </pre>
       *
       * <code>string errorMessage = 10;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 交易错误信息
       * </pre>
       *
       * <code>string errorMessage = 10;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易错误信息
       * </pre>
       *
       * <code>string errorMessage = 10;</code>
       */
      public Builder clearErrorMessage() {
        
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易错误信息
       * </pre>
       *
       * <code>string errorMessage = 10;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMessage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataStorageHash_ = "";
      /**
       * <pre>
       * 交易索引hash
       * </pre>
       *
       * <code>string dataStorageHash = 11;</code>
       */
      public java.lang.String getDataStorageHash() {
        java.lang.Object ref = dataStorageHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataStorageHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 交易索引hash
       * </pre>
       *
       * <code>string dataStorageHash = 11;</code>
       */
      public com.google.protobuf.ByteString
          getDataStorageHashBytes() {
        java.lang.Object ref = dataStorageHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataStorageHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 交易索引hash
       * </pre>
       *
       * <code>string dataStorageHash = 11;</code>
       */
      public Builder setDataStorageHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataStorageHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易索引hash
       * </pre>
       *
       * <code>string dataStorageHash = 11;</code>
       */
      public Builder clearDataStorageHash() {
        
        dataStorageHash_ = getDefaultInstance().getDataStorageHash();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易索引hash
       * </pre>
       *
       * <code>string dataStorageHash = 11;</code>
       */
      public Builder setDataStorageHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataStorageHash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <pre>
       * 交易时间戳转字符串——yyyy/MM/dd HH:mm:ss
       * </pre>
       *
       * <code>string time = 12;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 交易时间戳转字符串——yyyy/MM/dd HH:mm:ss
       * </pre>
       *
       * <code>string time = 12;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 交易时间戳转字符串——yyyy/MM/dd HH:mm:ss
       * </pre>
       *
       * <code>string time = 12;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易时间戳转字符串——yyyy/MM/dd HH:mm:ss
       * </pre>
       *
       * <code>string time = 12;</code>
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易时间戳转字符串——yyyy/MM/dd HH:mm:ss
       * </pre>
       *
       * <code>string time = 12;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private cn.aberic.bother.entity.proto.RequestProto.Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.aberic.bother.entity.proto.RequestProto.Request, cn.aberic.bother.entity.proto.RequestProto.Request.Builder, cn.aberic.bother.entity.proto.RequestProto.RequestOrBuilder> requestBuilder_;
      /**
       * <pre>
       * 智能合约请求对象
       * </pre>
       *
       * <code>.Request request = 13;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <pre>
       * 智能合约请求对象
       * </pre>
       *
       * <code>.Request request = 13;</code>
       */
      public cn.aberic.bother.entity.proto.RequestProto.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? cn.aberic.bother.entity.proto.RequestProto.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 智能合约请求对象
       * </pre>
       *
       * <code>.Request request = 13;</code>
       */
      public Builder setRequest(cn.aberic.bother.entity.proto.RequestProto.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 智能合约请求对象
       * </pre>
       *
       * <code>.Request request = 13;</code>
       */
      public Builder setRequest(
          cn.aberic.bother.entity.proto.RequestProto.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 智能合约请求对象
       * </pre>
       *
       * <code>.Request request = 13;</code>
       */
      public Builder mergeRequest(cn.aberic.bother.entity.proto.RequestProto.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              cn.aberic.bother.entity.proto.RequestProto.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 智能合约请求对象
       * </pre>
       *
       * <code>.Request request = 13;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 智能合约请求对象
       * </pre>
       *
       * <code>.Request request = 13;</code>
       */
      public cn.aberic.bother.entity.proto.RequestProto.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 智能合约请求对象
       * </pre>
       *
       * <code>.Request request = 13;</code>
       */
      public cn.aberic.bother.entity.proto.RequestProto.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              cn.aberic.bother.entity.proto.RequestProto.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <pre>
       * 智能合约请求对象
       * </pre>
       *
       * <code>.Request request = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.aberic.bother.entity.proto.RequestProto.Request, cn.aberic.bother.entity.proto.RequestProto.Request.Builder, cn.aberic.bother.entity.proto.RequestProto.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.aberic.bother.entity.proto.RequestProto.Request, cn.aberic.bother.entity.proto.RequestProto.Request.Builder, cn.aberic.bother.entity.proto.RequestProto.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private java.lang.Object pubECCKey_ = "";
      /**
       * <pre>
       * 账户 ECC 公钥
       * </pre>
       *
       * <code>string pubECCKey = 14;</code>
       */
      public java.lang.String getPubECCKey() {
        java.lang.Object ref = pubECCKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pubECCKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 账户 ECC 公钥
       * </pre>
       *
       * <code>string pubECCKey = 14;</code>
       */
      public com.google.protobuf.ByteString
          getPubECCKeyBytes() {
        java.lang.Object ref = pubECCKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pubECCKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 账户 ECC 公钥
       * </pre>
       *
       * <code>string pubECCKey = 14;</code>
       */
      public Builder setPubECCKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pubECCKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账户 ECC 公钥
       * </pre>
       *
       * <code>string pubECCKey = 14;</code>
       */
      public Builder clearPubECCKey() {
        
        pubECCKey_ = getDefaultInstance().getPubECCKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账户 ECC 公钥
       * </pre>
       *
       * <code>string pubECCKey = 14;</code>
       */
      public Builder setPubECCKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pubECCKey_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Transaction)
    }

    // @@protoc_insertion_point(class_scope:Transaction)
    private static final cn.aberic.bother.entity.proto.TransactionProto.Transaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.aberic.bother.entity.proto.TransactionProto.Transaction();
    }

    public static cn.aberic.bother.entity.proto.TransactionProto.Transaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transaction>
        PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
      @java.lang.Override
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.aberic.bother.entity.proto.TransactionProto.Transaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Transaction.proto\032\013RWSet.proto\032\rReques" +
      "t.proto\"\371\002\n\013Transaction\022\014\n\004hash\030\001 \001(\t\022\024\n" +
      "\014contractName\030\002 \001(\t\022\027\n\017contractVersion\030\003" +
      " \001(\t\022\017\n\007creator\030\004 \001(\t\022\014\n\004sign\030\005 \001(\t\022\025\n\005r" +
      "wSet\030\006 \001(\0132\006.RWSet\022\021\n\ttimestamp\030\007 \001(\004\022\016\n" +
      "\006txHash\030\010 \001(\t\022=\n\025transactionStatusCode\030\t" +
      " \001(\0162\036.Transaction.TransactionStatus\022\024\n\014" +
      "errorMessage\030\n \001(\t\022\027\n\017dataStorageHash\030\013 " +
      "\001(\t\022\014\n\004time\030\014 \001(\t\022\031\n\007request\030\r \001(\0132\010.Req" +
      "uest\022\021\n\tpubECCKey\030\016 \001(\t\"*\n\021TransactionSt" +
      "atus\022\013\n\007SUCCESS\020\000\022\010\n\004FAIL\020\001B1\n\035cn.aberic" +
      ".bother.entity.protoB\020TransactionProtob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.aberic.bother.entity.proto.RWSetProto.getDescriptor(),
          cn.aberic.bother.entity.proto.RequestProto.getDescriptor(),
        }, assigner);
    internal_static_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transaction_descriptor,
        new java.lang.String[] { "Hash", "ContractName", "ContractVersion", "Creator", "Sign", "RwSet", "Timestamp", "TxHash", "TransactionStatusCode", "ErrorMessage", "DataStorageHash", "Time", "Request", "PubECCKey", });
    cn.aberic.bother.entity.proto.RWSetProto.getDescriptor();
    cn.aberic.bother.entity.proto.RequestProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
