/*
 * MIT License
 *
 * Copyright (c) 2018 Aberic Yang
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consensus/JoinNode.proto

package cn.aberic.bother.entity.proto.consensus;

public final class JoinNodeProto {
  private JoinNodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JoinNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JoinNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 节点地址
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    String getAddress();
    /**
     * <pre>
     * 节点地址
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * 加入节点所在级别
     * </pre>
     *
     * <code>.JoinNode.JoinLevel level = 2;</code>
     */
    int getLevelValue();
    /**
     * <pre>
     * 加入节点所在级别
     * </pre>
     *
     * <code>.JoinNode.JoinLevel level = 2;</code>
     */
    JoinNodeProto.JoinNode.JoinLevel getLevel();
  }
  /**
   * <pre>
   * 加入节点对象
   * </pre>
   *
   * Protobuf type {@code JoinNode}
   */
  public  static final class JoinNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JoinNode)
      JoinNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JoinNode.newBuilder() to construct.
    private JoinNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JoinNode() {
      address_ = "";
      level_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JoinNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              level_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JoinNodeProto.internal_static_JoinNode_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JoinNodeProto.internal_static_JoinNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JoinNodeProto.JoinNode.class, JoinNodeProto.JoinNode.Builder.class);
    }

    /**
     * Protobuf enum {@code JoinNode.JoinLevel}
     */
    public enum JoinLevel
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 孤岛
       * </pre>
       *
       * <code>LONEY = 0;</code>
       */
      LONEY(0),
      /**
       * <pre>
       * 楼
       * </pre>
       *
       * <code>TOWER = 1;</code>
       */
      TOWER(1),
      /**
       * <pre>
       * 社区
       * </pre>
       *
       * <code>COMMUNITY = 2;</code>
       */
      COMMUNITY(2),
      /**
       * <pre>
       * 县城
       * </pre>
       *
       * <code>COUNTY = 3;</code>
       */
      COUNTY(3),
      /**
       * <pre>
       * 市
       * </pre>
       *
       * <code>CITY = 4;</code>
       */
      CITY(4),
      /**
       * <pre>
       * 省
       * </pre>
       *
       * <code>PROVINCE = 5;</code>
       */
      PROVINCE(5),
      /**
       * <pre>
       * 楼，无需处理
       * </pre>
       *
       * <code>TOWER_NO_EXEC = 6;</code>
       */
      TOWER_NO_EXEC(6),
      /**
       * <pre>
       * 社区，无需处理
       * </pre>
       *
       * <code>COMMUNITY_NO_EXEC = 7;</code>
       */
      COMMUNITY_NO_EXEC(7),
      /**
       * <pre>
       * 县城，无需处理
       * </pre>
       *
       * <code>COUNTY_NO_EXEC = 8;</code>
       */
      COUNTY_NO_EXEC(8),
      /**
       * <pre>
       * 市，无需处理
       * </pre>
       *
       * <code>CITY_NO_EXEC = 9;</code>
       */
      CITY_NO_EXEC(9),
      /**
       * <pre>
       * 省，无需处理
       * </pre>
       *
       * <code>PROVINCE_NO_EXEC = 10;</code>
       */
      PROVINCE_NO_EXEC(10),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 孤岛
       * </pre>
       *
       * <code>LONEY = 0;</code>
       */
      public static final int LONEY_VALUE = 0;
      /**
       * <pre>
       * 楼
       * </pre>
       *
       * <code>TOWER = 1;</code>
       */
      public static final int TOWER_VALUE = 1;
      /**
       * <pre>
       * 社区
       * </pre>
       *
       * <code>COMMUNITY = 2;</code>
       */
      public static final int COMMUNITY_VALUE = 2;
      /**
       * <pre>
       * 县城
       * </pre>
       *
       * <code>COUNTY = 3;</code>
       */
      public static final int COUNTY_VALUE = 3;
      /**
       * <pre>
       * 市
       * </pre>
       *
       * <code>CITY = 4;</code>
       */
      public static final int CITY_VALUE = 4;
      /**
       * <pre>
       * 省
       * </pre>
       *
       * <code>PROVINCE = 5;</code>
       */
      public static final int PROVINCE_VALUE = 5;
      /**
       * <pre>
       * 楼，无需处理
       * </pre>
       *
       * <code>TOWER_NO_EXEC = 6;</code>
       */
      public static final int TOWER_NO_EXEC_VALUE = 6;
      /**
       * <pre>
       * 社区，无需处理
       * </pre>
       *
       * <code>COMMUNITY_NO_EXEC = 7;</code>
       */
      public static final int COMMUNITY_NO_EXEC_VALUE = 7;
      /**
       * <pre>
       * 县城，无需处理
       * </pre>
       *
       * <code>COUNTY_NO_EXEC = 8;</code>
       */
      public static final int COUNTY_NO_EXEC_VALUE = 8;
      /**
       * <pre>
       * 市，无需处理
       * </pre>
       *
       * <code>CITY_NO_EXEC = 9;</code>
       */
      public static final int CITY_NO_EXEC_VALUE = 9;
      /**
       * <pre>
       * 省，无需处理
       * </pre>
       *
       * <code>PROVINCE_NO_EXEC = 10;</code>
       */
      public static final int PROVINCE_NO_EXEC_VALUE = 10;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static JoinLevel valueOf(int value) {
        return forNumber(value);
      }

      public static JoinLevel forNumber(int value) {
        switch (value) {
          case 0: return LONEY;
          case 1: return TOWER;
          case 2: return COMMUNITY;
          case 3: return COUNTY;
          case 4: return CITY;
          case 5: return PROVINCE;
          case 6: return TOWER_NO_EXEC;
          case 7: return COMMUNITY_NO_EXEC;
          case 8: return COUNTY_NO_EXEC;
          case 9: return CITY_NO_EXEC;
          case 10: return PROVINCE_NO_EXEC;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<JoinLevel>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          JoinLevel> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<JoinLevel>() {
              public JoinLevel findValueByNumber(int number) {
                return JoinLevel.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return JoinNodeProto.JoinNode.getDescriptor().getEnumTypes().get(0);
      }

      private static final JoinLevel[] VALUES = values();

      public static JoinLevel valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private JoinLevel(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:JoinNode.JoinLevel)
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile Object address_;
    /**
     * <pre>
     * 节点地址
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 节点地址
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    /**
     * <pre>
     * 加入节点所在级别
     * </pre>
     *
     * <code>.JoinNode.JoinLevel level = 2;</code>
     */
    public int getLevelValue() {
      return level_;
    }
    /**
     * <pre>
     * 加入节点所在级别
     * </pre>
     *
     * <code>.JoinNode.JoinLevel level = 2;</code>
     */
    public JoinNodeProto.JoinNode.JoinLevel getLevel() {
      @SuppressWarnings("deprecation")
      JoinNodeProto.JoinNode.JoinLevel result = JoinNodeProto.JoinNode.JoinLevel.valueOf(level_);
      return result == null ? JoinNodeProto.JoinNode.JoinLevel.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (level_ != JoinNodeProto.JoinNode.JoinLevel.LONEY.getNumber()) {
        output.writeEnum(2, level_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (level_ != JoinNodeProto.JoinNode.JoinLevel.LONEY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, level_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof JoinNodeProto.JoinNode)) {
        return super.equals(obj);
      }
      JoinNodeProto.JoinNode other = (JoinNodeProto.JoinNode) obj;

      boolean result = true;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && level_ == other.level_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + level_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static JoinNodeProto.JoinNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JoinNodeProto.JoinNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JoinNodeProto.JoinNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JoinNodeProto.JoinNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JoinNodeProto.JoinNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JoinNodeProto.JoinNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JoinNodeProto.JoinNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static JoinNodeProto.JoinNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static JoinNodeProto.JoinNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static JoinNodeProto.JoinNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static JoinNodeProto.JoinNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static JoinNodeProto.JoinNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(JoinNodeProto.JoinNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 加入节点对象
     * </pre>
     *
     * Protobuf type {@code JoinNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JoinNode)
        JoinNodeProto.JoinNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JoinNodeProto.internal_static_JoinNode_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JoinNodeProto.internal_static_JoinNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                JoinNodeProto.JoinNode.class, JoinNodeProto.JoinNode.Builder.class);
      }

      // Construct using cn.aberic.bother.entity.proto.consensus.JoinNodeProto.JoinNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        address_ = "";

        level_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JoinNodeProto.internal_static_JoinNode_descriptor;
      }

      @Override
      public JoinNodeProto.JoinNode getDefaultInstanceForType() {
        return JoinNodeProto.JoinNode.getDefaultInstance();
      }

      @Override
      public JoinNodeProto.JoinNode build() {
        JoinNodeProto.JoinNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public JoinNodeProto.JoinNode buildPartial() {
        JoinNodeProto.JoinNode result = new JoinNodeProto.JoinNode(this);
        result.address_ = address_;
        result.level_ = level_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JoinNodeProto.JoinNode) {
          return mergeFrom((JoinNodeProto.JoinNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(JoinNodeProto.JoinNode other) {
        if (other == JoinNodeProto.JoinNode.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.level_ != 0) {
          setLevelValue(other.getLevelValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        JoinNodeProto.JoinNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (JoinNodeProto.JoinNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object address_ = "";
      /**
       * <pre>
       * 节点地址
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 节点地址
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 节点地址
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 节点地址
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public Builder clearAddress() {

        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 节点地址
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        address_ = value;
        onChanged();
        return this;
      }

      private int level_ = 0;
      /**
       * <pre>
       * 加入节点所在级别
       * </pre>
       *
       * <code>.JoinNode.JoinLevel level = 2;</code>
       */
      public int getLevelValue() {
        return level_;
      }
      /**
       * <pre>
       * 加入节点所在级别
       * </pre>
       *
       * <code>.JoinNode.JoinLevel level = 2;</code>
       */
      public Builder setLevelValue(int value) {
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 加入节点所在级别
       * </pre>
       *
       * <code>.JoinNode.JoinLevel level = 2;</code>
       */
      public JoinNodeProto.JoinNode.JoinLevel getLevel() {
        @SuppressWarnings("deprecation")
        JoinNodeProto.JoinNode.JoinLevel result = JoinNodeProto.JoinNode.JoinLevel.valueOf(level_);
        return result == null ? JoinNodeProto.JoinNode.JoinLevel.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 加入节点所在级别
       * </pre>
       *
       * <code>.JoinNode.JoinLevel level = 2;</code>
       */
      public Builder setLevel(JoinNodeProto.JoinNode.JoinLevel value) {
        if (value == null) {
          throw new NullPointerException();
        }

        level_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 加入节点所在级别
       * </pre>
       *
       * <code>.JoinNode.JoinLevel level = 2;</code>
       */
      public Builder clearLevel() {

        level_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JoinNode)
    }

    // @@protoc_insertion_point(class_scope:JoinNode)
    private static final JoinNodeProto.JoinNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new JoinNodeProto.JoinNode();
    }

    public static JoinNodeProto.JoinNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JoinNode>
        PARSER = new com.google.protobuf.AbstractParser<JoinNode>() {
      @Override
      public JoinNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JoinNode> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<JoinNode> getParserForType() {
      return PARSER;
    }

    @Override
    public JoinNodeProto.JoinNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JoinNode_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JoinNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030consensus/JoinNode.proto\"\374\001\n\010JoinNode\022" +
      "\017\n\007address\030\001 \001(\t\022\"\n\005level\030\002 \001(\0162\023.JoinNo" +
      "de.JoinLevel\"\272\001\n\tJoinLevel\022\t\n\005LONEY\020\000\022\t\n" +
      "\005TOWER\020\001\022\r\n\tCOMMUNITY\020\002\022\n\n\006COUNTY\020\003\022\010\n\004C" +
      "ITY\020\004\022\014\n\010PROVINCE\020\005\022\021\n\rTOWER_NO_EXEC\020\006\022\025" +
      "\n\021COMMUNITY_NO_EXEC\020\007\022\022\n\016COUNTY_NO_EXEC\020" +
      "\010\022\020\n\014CITY_NO_EXEC\020\t\022\024\n\020PROVINCE_NO_EXEC\020" +
      "\nB8\n\'cn.aberic.bother.entity.proto.conse" +
      "nsusB\rJoinNodeProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JoinNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JoinNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JoinNode_descriptor,
        new String[] { "Address", "Level", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
